---
kind: pipeline
name: default

steps:
- name: build
  image: car2x/docker-veins-0.0.4:d10-v5.0-o5.6.1-s1.5.0
  commands:
    - export PATH="$PATH:/opt/omnetpp/bin:/opt/sumo/bin"
    - apt-get update && apt-get install -y python3-pip python3-wheel protobuf-compiler libprotobuf-dev libzmq3-dev
    - python3 -m pip install snakemake
    - snakemake -jall

- name: notebook
  image: car2x/docker-veins-0.0.4:d10-v5.0-o5.6.1-s1.5.0
  commands:
    - export PATH="$PATH:/opt/omnetpp/bin:/opt/sumo/bin"
    - apt-get update && apt-get install -y python3-pip python3-wheel libprotobuf-dev libzmq3-dev
    - python3 -m pip install veins_gym nbconvert ipykernel
    - jupyter nbconvert --to markdown --execute examples/Tutorial_Using_the_Serpentine_Scenario.ipynb
    - cat examples/Tutorial_Using_the_Serpentine_Scenario.md
